### ISSUE TITLE
./krack-test-client.py Error

### ISSUE THREAD

**Issue by CanSJun** [vanhoefm/krackattacks-scripts#101]
Adaptor : Archer T9UH Adaptor 
Kali linux 2023 

**information : iw list**

Wiphy phy0
        wiphy index: 0
        max # scan SSIDs: 9
        max scan IEs length: 2304 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
                * CMAC (00-0f-ac:6)
        Available Antennas: TX 0x4 RX 0x4
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * monitor
                 * P2P-client
                 * P2P-GO
        Band 1:
                Capabilities: 0x1b73
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX Greenfield
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 3-streams
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 16 usec (0x07)
                HT Max RX data rate: 450 Mbps
                HT TX/RX MCS rate indexes supported: 0-23
                Bitrates (non-HT):
                        * 1.0 Mbps
                        * 2.0 Mbps
                        * 5.5 Mbps
                        * 11.0 Mbps
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 2412 MHz [1] (20.0 dBm)
                        * 2417 MHz [2] (20.0 dBm)
                        * 2422 MHz [3] (20.0 dBm)
                        * 2427 MHz [4] (20.0 dBm)
                        * 2432 MHz [5] (20.0 dBm)
                        * 2437 MHz [6] (20.0 dBm)
                        * 2442 MHz [7] (20.0 dBm)
                        * 2447 MHz [8] (20.0 dBm)
                        * 2452 MHz [9] (20.0 dBm)
                        * 2457 MHz [10] (20.0 dBm)
                        * 2462 MHz [11] (20.0 dBm)
                        * 2467 MHz [12] (20.0 dBm)
                        * 2472 MHz [13] (20.0 dBm)
                        * 2484 MHz [14] (20.0 dBm)
        Band 2:
                Capabilities: 0x1b73
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX Greenfield
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 3-streams
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 16 usec (0x07)
                HT Max RX data rate: 450 Mbps
                HT TX/RX MCS rate indexes supported: 0-23
                VHT Capabilities (0x03c054b2):
                        Max MPDU length: 11454
                        Supported Channel Width: neither 160 nor 80+80
                        RX LDPC
                        short GI (80 MHz)
                        TX STBC
                        SU Beamformee
                        +HTC-VHT
                VHT RX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: MCS 0-9
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT RX highest supported: 1300 Mbps
                VHT TX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: MCS 0-9
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT TX highest supported: 1300 Mbps
                VHT extended NSS: not supported
                Bitrates (non-HT):
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 5075 MHz [15] (30.0 dBm)
                        * 5080 MHz [16] (30.0 dBm)
                        * 5085 MHz [17] (30.0 dBm)
                        * 5090 MHz [18] (30.0 dBm)
                        * 5100 MHz [20] (30.0 dBm)
                        * 5120 MHz [24] (30.0 dBm)
                        * 5140 MHz [28] (30.0 dBm)
                        * 5160 MHz [32] (30.0 dBm)
                        * 5180 MHz [36] (30.0 dBm)
                        * 5200 MHz [40] (30.0 dBm)
                        * 5220 MHz [44] (30.0 dBm)
                        * 5240 MHz [48] (30.0 dBm)
                        * 5260 MHz [52] (30.0 dBm)
                        * 5280 MHz [56] (30.0 dBm)
                        * 5300 MHz [60] (30.0 dBm)
                        * 5320 MHz [64] (30.0 dBm)
                        * 5340 MHz [68] (30.0 dBm)
                        * 5360 MHz [72] (30.0 dBm)
                        * 5380 MHz [76] (30.0 dBm)
                        * 5400 MHz [80] (30.0 dBm)
                        * 5420 MHz [84] (30.0 dBm)
                        * 5440 MHz [88] (30.0 dBm)
                        * 5460 MHz [92] (30.0 dBm)
                        * 5480 MHz [96] (30.0 dBm)
                        * 5500 MHz [100] (30.0 dBm)
                        * 5520 MHz [104] (30.0 dBm)
                        * 5540 MHz [108] (30.0 dBm)
                        * 5560 MHz [112] (30.0 dBm)
                        * 5580 MHz [116] (30.0 dBm)
                        * 5600 MHz [120] (30.0 dBm)
                        * 5620 MHz [124] (30.0 dBm)
                        * 5640 MHz [128] (30.0 dBm)
                        * 5660 MHz [132] (30.0 dBm)
                        * 5680 MHz [136] (30.0 dBm)
                        * 5700 MHz [140] (30.0 dBm)
                        * 5720 MHz [144] (30.0 dBm)
                        * 5745 MHz [149] (30.0 dBm)
                        * 5765 MHz [153] (30.0 dBm)
                        * 5785 MHz [157] (30.0 dBm)
                        * 5805 MHz [161] (30.0 dBm)
                        * 5825 MHz [165] (30.0 dBm)
                        * 5845 MHz [169] (30.0 dBm)
                        * 5865 MHz [173] (30.0 dBm)
                        * 5885 MHz [177] (30.0 dBm)
        Supported commands:
                 * set_interface
                 * new_key
                 * start_ap
                 * new_station
                 * set_bss
                 * join_ibss
                 * set_pmksa
                 * del_pmksa
                 * flush_pmksa
                 * remain_on_channel
                 * frame
                 * set_wiphy_netns
                 * set_channel
                 * connect
                 * disconnect
        WoWLAN support:
                 * wake up on anything (device continues operating normally)
        software interface modes (can always be added):
                 * monitor
        interface combinations are not supported
        Device supports SAE with AUTHENTICATE command
        Device supports scan flush.
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Supported TX frame types:
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
        Supported RX frame types:
                 * IBSS: 0xd0
                 * managed: 0x40 0xb0 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
        Supported extended features:

problems : 
------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------

**if wlan0 type is managed** 

phy#0
        Interface wlan0
                ifindex 3
                wdev 0x1
                addr 7c:c2:c6:39:a5:da
                type managed
                channel 2 (2417 MHz), width: 40 MHz, center1: 2427 MHz
                txpower 20.00 dBm

------------------------------------------------------------------------------------------------------------------------------

┌──(venv)─(root㉿kali)-[/home/kali/krackattacks-scripts/krackattack]
└─# ./krack-test-client.py --tptk
[04:40:47] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
command failed: Operation not supported (-95)
Traceback (most recent call last):
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 663, in <module>
    attack.run(options=options)
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 465, in run
    self.configure_interfaces()
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 455, in configure_interfaces
    subprocess.check_output(["iw", self.nic_iface, "interface", "add", self.nic_mon, "type", "monitor"])
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['iw', 'wlan0', 'interface', 'add', 'monwlan0', 'type', 'monitor']' returned non-zero exit status 161.
[04:40:47] Closing hostapd and cleaning up ...

------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------

**if wlan0 type is monitor** 
phy#0
        Interface wlan0
                ifindex 3
                wdev 0x1
                addr 7c:c2:c6:39:a5:da
                type monitor
                channel 2 (2417 MHz), width: 40 MHz, center1: 2427 MHz
                txpower 20.00 dBm

----------------------------------------------------------------------------------------------------------------------------------

./krack-test-client.py --tptk    
[04:42:39] Failed to get MAC address of wlan0. Specify an existing interface in hostapd.conf at the line "interface=NAME".                                
Traceback (most recent call last):
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 661, in <module>
    attack = KRAckAttackClient()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 277, in __init__
    self.apmac = scapy.arch.get_if_hwaddr(interface)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/krackattacks-scripts/krackattack/venv/lib/python3.11/site-packages/scapy/arch/__init__.py", line 39, in get_if_hwaddr
    raise Scapy_Exception("Unsupported address family (%i) for interface [%s]" % (addrfamily, iff))  # noqa: E501
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
scapy.error.Scapy_Exception: Unsupported address family (803) for interface [wlan0]

**Comment by vanhoefm** [comment]
This is a late reply, but did you ensure that there are no other running processes that are using the Wi-Fi card? In particular, turning off Wi-Fi in the network manager?

Update: with my own Wi-Fi dongle, I've noticed that unplugging and re-inserting the Wi-Fi dongle might help.
