### ISSUE TITLE
NameError: name 'L2Socket' is not defined

### ISSUE THREAD

**Issue by Diablox00** [vanhoefm/krackattacks-scripts#106]
Traceback (most recent call last):
  File "/home/diablo/scripts/hacks/wireless/wifi/krackattacks-scripts/krackattack/./krack-test-client.py", line 12, in <module>
    import libwifi
  File "/home/diablo/scripts/hacks/wireless/wifi/krackattacks-scripts/krackattack/libwifi/__init__.py", line 1, in <module>
    from .wifi import *
  File "/home/diablo/scripts/hacks/wireless/wifi/krackattacks-scripts/krackattack/libwifi/wifi.py", line 204, in <module>
    class MonitorSocket(L2Socket):
                        ^^^^^^^^
NameError: name 'L2Socket' is not defined

**Comment by vanhoefm** [comment]
You're likely not using the virtual python environment `source venv/bin/activate` before running the script. Based on your second report this works now, so closing this.
