### ISSUE TITLE
Failed to get MAC address of wlx14ebb69518b7

### ISSUE THREAD

**Issue by Diablox00** [vanhoefm/krackattacks-scripts#107]
└──╼ #./krack-test-client.py 
[11:27:32] Failed to get MAC address of wlx14ebb69518b7. Specify an existing interface in hostapd.conf at the line "interface=NAME".
Traceback (most recent call last):
  File "/home/diablo/Documents/krackattacks-scripts/krackattack/./krack-test-client.py", line 661, in <module>
    attack = KRAckAttackClient()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/diablo/Documents/krackattacks-scripts/krackattack/./krack-test-client.py", line 277, in __init__
    self.apmac = scapy.arch.get_if_hwaddr(interface)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diablo/Documents/krackattacks-scripts/krackattack/venv/lib/python3.11/site-packages/scapy/arch/__init__.py", line 39, in get_if_hwaddr
    raise Scapy_Exception("Unsupported address family (%i) for interface [%s]" % (addrfamily, iff))  # noqa: E501
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
scapy.error.Scapy_Exception: Unsupported address family (803) for interface [wlx14ebb69518b7]
(venv) ┌─[✗]─[root@parrot]─[/home/diablo/Documents/krackattacks-scripts/krackattack]

**Comment by vanhoefm** [comment]
Does your network card support monitor mode? Which network card are you using: what is the output of `lspci` and `lsusb`?
