### ISSUE TITLE
krack-test-client.py not working

### ISSUE THREAD

**Issue by ghost** [vanhoefm/krackattacks-scripts#20]
I have a problem with this script. I did the latest updates as well as installed recommended files but no go. Can I please ask for your assistance ? Kindest regards and thank you for your hard work. 

uname -a
Linux parrot 4.13.0-parrot4-amd64 #1 SMP Parrot 4.13.4-2parrot0 (2017-10-17) x86_64 GNU/Linux

/krack-test-client.py
Traceback (most recent call last):
  File "./krack-test-client.py", line 612, in <module>
    attack.run(test_grouphs=test_grouphs, test_tptk=test_tptk)
  File "./krack-test-client.py", line 461, in run
    self.configure_interfaces()
  File "./krack-test-client.py", line 443, in configure_interfaces
    log(STATUS, "Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.")
  File "/home/parrot/Downloads/krackattacks-scripts-research/krackattack/libwifi.py", line 22, in log
    print (datetime.now().strftime('[%H:%M:%S] ') if showtime else " "*11) + COLORCODES.get(color, "") + msg + "\033[1;0m"
NameError: global name 'datetime' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./krack-test-client.py", line 542, in cleanup
    attack.stop()
  File "./krack-test-client.py", line 533, in stop
    log(STATUS, "Closing hostapd and cleaning up ...")
  File "/home/parrot/Downloads/krackattacks-scripts-research/krackattack/libwifi.py", line 22, in log
    print (datetime.now().strftime('[%H:%M:%S] ') if showtime else " "*11) + COLORCODES.get(color, "") + msg + "\033[1;0m"
NameError: global name 'datetime' is not defined
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./krack-test-client.py", line 542, in cleanup
    attack.stop()
  File "./krack-test-client.py", line 533, in stop
    log(STATUS, "Closing hostapd and cleaning up ...")
  File "/home/parrot/Downloads/krackattacks-scripts-research/krackattack/libwifi.py", line 22, in log
    print (datetime.now().strftime('[%H:%M:%S] ') if showtime else " "*11) + COLORCODES.get(color, "") + msg + "\033[1;0m"
NameError: global name 'datetime' is not defined

**Comment by vanhoefm** [comment]
Only Kali Linux is officially supported. Your version of scapy might be out of date. Try running the script for a Kali Linux virtual machine.
