### ISSUE TITLE
ImportError: No module named Cryptodome.Cipher

### ISSUE THREAD

**Issue by SImpleZibs** [vanhoefm/krackattacks-scripts#29]
Hi,
As i was trying to run the script for the first time, **./krack-ft-test.py,** and the result is:
_Traceback (most recent call last):
  File "./krack-ft-test.py", line 11, in <module>
    from libwifi import *
  File "/root/Desktop/krackattacks-scripts-research/krackattack/libwifi.py", line 6, in <module>
    from Cryptodome.Cipher import AES
ImportError: No module named Cryptodome.Cipher_

I try'd to update like was said in the instructions, **apt-get install libnl-3-dev libnl-genl-3-dev pkg-config libssl-dev net-tools git sysfsutils python-scapy python-pycryptodome**
, and the result is:
_Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pkg-config is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libnl-3-dev
E: Unable to locate package libnl-genl-3-dev
E: Package 'pkg-config' has no installation candidate
E: Unable to locate package libssl-dev
E: Unable to locate package sysfsutils
E: Unable to locate package python-pycryptodome_

Anyone knows why this is appening?

**Comment by SImpleZibs** [comment]
find it!
search how to fix the repository error on kali
