### ISSUE TITLE
how to fix error python2 krack-test-client.py Failed to get MAC address of wlan0.....

### ISSUE THREAD

**Issue by Mrvu182hp** [vanhoefm/krackattacks-scripts#48]
please help me
how to fix error setup script on ubutu 16.04
~/krackattacks-scripts/krackattack$ python2 krack-test-client.py
[10:48:07] Failed to get MAC address of wlan0. Specify an existing interface in hostapd.conf at the line "interface=NAME".
Traceback (most recent call last):
  File "krack-test-client.py", line 615, in <module>
    attack = KRAckAttackClient()
  File "krack-test-client.py", line 349, in __init__
    self.apmac = scapy.arch.get_if_hwaddr(interface)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/arch/__init__.py", line 32, in get_if_hwaddr
    addrfamily, mac = get_if_raw_hwaddr(iff)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/arch/linux.py", line 105, in get_if_raw_hwaddr
    return struct.unpack("16xh6s8x",get_if(iff,SIOCGIFHWADDR))
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/arch/common.py", line 22, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
IOError: [Errno 19] No such device

AND error for use command from help option 
~/krackattacks-scripts/krackattack$ python2 krack-test-client.py --help

v4k@v4k:~/krackattacks-scripts/hostapd$ cd ../hostapd
v4k@v4k:~/krackattacks-scripts/hostapd$ cp defconfig .config
v4k@v4k:~/krackattacks-scripts/hostapd$ make -j 2
fatal: No names found, cannot describe anything.

please help me how to fix 
thank a lot

**Comment by r0b78** [comment]
this work to do the test 
macchanger -s wlan0

**Comment by 999khem** [comment]
i think you should specify wlan0 in interface=NAME
eg. interface=wlan0

**Comment by vanhoefm** [comment]
Looks like the interface `wlan0` does not exist. So indeed try specifying the correct interface in `hostapd.conf`.
