### ISSUE TITLE
No such device error: krack-test-client.py

### ISSUE THREAD

**Issue by CrystalGhost** [vanhoefm/krackattacks-scripts#60]
I don't understand why it keeps telling me "No such device". Is there a problem with the code? I've gone through all the steps correctly. 

Using interface wlan0 with hwaddr 00:c0:ca:84:8a:ad and ssid "testnetwork"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
Traceback (most recent call last):
  File "./krack-test-client.py", line 609, in <module>
    attack.run(options=options)
  File "./krack-test-client.py", line 447, in run
    self.sock_mon = MitmSocket(type=ETH_P_ALL, iface=self.nic_mon)
  File "/home/damazo/krackattacks-scripts-research/krackattack/libwifi.py", line 75, in __init__
    super(MitmSocket, self).__init__(**kwargs)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 514, in __init__
    set_promisc(self.ins, self.iface)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 168, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 375, in get_if_index
    return int(struct.unpack("I",get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 24, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
IOError: [Errno 19] No such device
[20:35:03] Closing hostapd and cleaning up ...
wlan0: interface state ENABLED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlan0 disabled_11b_rates=0

I can't find anyone who has resolved this error. If there are any other steps that I have might missed please let me know. Help is much appreciated, Thank You.  

4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux

**Comment by harpyja** [comment]
I have seen this problem before. I resolved it by re-clone the program and change the dongle device.

**Comment by vanhoefm** [comment]
Closing due to age. Make sure you disabled Wi-Fi and the interface is not in use.
