### ISSUE TITLE
About ./krack-test-client.py

### ISSUE THREAD

**Issue by RMSJ001** [vanhoefm/krackattacks-scripts#63]
it's a error for my test on kali linux
root@kali:~/Desktop/krackattacks-scripts-research/krackattack# ./krack-test-client.py 
[14:33:26] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
[14:33:27] Starting hostapd ...
Configuration file: /root/Desktop/krackattacks-scripts-research/krackattack/hostapd.conf
Line 1: invalid line 'n##### hostapd configuration file ##############################################'
1 errors found in configuration file '/root/Desktop/krackattacks-scripts-research/krackattack/hostapd.conf'
Failed to set up interface with /root/Desktop/krackattacks-scripts-research/krackattack/hostapd.conf
Failed to initialize interface
connect exception  hostapd_ctrl/wlan0 9877
[14:33:48] It seems hostapd did not start properly, please inspect its output.
[14:33:48] Did you disable Wi-Fi in the network manager? Otherwise hostapd won't work.
Traceback (most recent call last):
  File "./krack-test-client.py", line 609, in <module>
    attack.run(options=options)
  File "./krack-test-client.py", line 440, in run
    self.hostapd_ctrl = Ctrl("hostapd_ctrl/" + self.nic_iface)
  File "/root/Desktop/krackattacks-scripts-research/krackattack/wpaspy.py", line 51, in __init__
    socket.SOCK_DGRAM)
socket.gaierror: [Errno -2] Name or service not known
[14:33:48] Closing hostapd and cleaning up ...

Device 002: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter.
And Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * mesh point

How can I fix it?  Thanks.

**Comment by vanhoefm** [comment]
Looks like this was caused by an invalid `hostapd.conf` file. Use a clean unedited version of this file and try running it again.
