### ISSUE TITLE
IndexError: Layer [Dot11Encrypted] not found

### ISSUE THREAD

**Issue by mugiwara85** [vanhoefm/krackattacks-scripts#77]
Hello,

when I start the script, and a client connects I immediately get the following error:
`[14:21:34] 50:eb:71:f8:e8:eb: 4-way handshake completed (RSN)
Traceback (most recent call last):  
  File "./krackattacks-scripts/krackattack/krack-test-client.py", line 625, in <module>  
    attack.run(options=options)  
  File "./krackattacks-scripts/krackattack/krack-test-client.py", line 485, in run  
    if self.sock_mon in sel[0]: self.handle_mon_rx()  
  File "./krackattacks-scripts/krackattack/krack-test-client.py", line 354, in handle_mon_rx  
    iv = dot11_get_iv(p)  
  File "/home/zsolt/krackattacks-scripts/krackattack/libwifi.py", line 154, in dot11_get_iv  
    payload = str(p[Dot11Encrypted])  
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 1171, in __getitem__  
    raise IndexError("Layer [%s] not found" % lname)  
IndexError: Layer [Dot11Encrypted] not found  
[14:21:34] Closing hostapd and cleaning up ...`

Does anyone has any idea how to solve this? I'm stuck here, and found no solution anywhere. I am using Kali Linux 2020.2.

Thanks in advance!

**Comment by mugiwara85** [comment]
Never mind, figured it out.

**Comment by vanhoefm** [comment]
Hi kampi85, glad that you figured it out. Can you post what went wrong, in case others face the same issue?

**Comment by mugiwara85** [comment]
Hi,
of course. I did the almost the same thing as Gabba90 described here: https://github.com/vanhoefm/krackattacks-scripts/issues/71#issuecomment-533591576
I replaced scapy 2.4.3 with an older version 2.4.0. The only difference was, that I didn't use the command `apt-get install python-pip` but rather `pip uninstall python-pip`
Now everything is working fine.

**Comment by pococ31** [comment]
@mugiwara85 
Hi
Can you mention the WiFi Adapter and driver version that you used with krackattack script.
