### ISSUE TITLE
Issue with krack-test-client.py

### ISSUE THREAD

**Issue by Hellstormer00** [vanhoefm/krackattacks-scripts#83]
I did everything as described. I didn't touch the hostapd.conf because my Wifi is called wlan0 in iwconfig.
But when I run krack-test-client-py I get the following Error message. I alredy recloned the github repo and replaced the hostapd.conf for a new one.

[18:10:11] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
[18:10:12] Starting hostapd ...
Configuration file: /home/kali/wifi/krackattacks-scripts/krackattack/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started
connect exception  hostapd_ctrl/wlan0 9877
[18:10:13] It seems hostapd did not start properly, please inspect its output.                                                                            
[18:10:13] Did you disable Wi-Fi in the network manager? Otherwise hostapd won't work.                                                                    
Traceback (most recent call last):
  File "/home/kali/wifi/krackattacks-scripts/krackattack/./krack-test-client.py", line 628, in <module>
    attack.run(options=options)
  File "/home/kali/wifi/krackattacks-scripts/krackattack/./krack-test-client.py", line 446, in run
    self.hostapd_ctrl = Ctrl("hostapd_ctrl/" + self.nic_iface)
  File "/home/kali/wifi/krackattacks-scripts/krackattack/wpaspy.py", line 50, in __init__
    ai_list = socket.getaddrinfo(path, port, socket.AF_INET,
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
[18:10:13] Closing hostapd and cleaning up ...

**Comment by vanhoefm** [comment]
Does your wireless network card support "access point mode"? You can check by copying the output of `iw list` here and looking if "AP" is listed under "Supported interface modes".

**Comment by vanhoefm** [comment]
Closed due to no further response.
