### ISSUE TITLE
krack-test-client.py does not work does not work from the beginning

### ISSUE THREAD

**Issue by PapaOfficial** [vanhoefm/krackattacks-scripts#91]
When I run the script krack-test-client.py here is the output:

[11:26:02] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.

And then it just freezes permanently, if I click ctrl+c here is the output:

^CTraceback (most recent call last):
File "/home/kali/krackattacks-scripts/krackattack/./[krack-test-client.py](http://krack-test-client.py/)", line 663, in <module>
[attack.run](http://attack.run/)(options=options)
File "/home/kali/krackattacks-scripts/krackattack/./[krack-test-client.py](http://krack-test-client.py/)", line 465, in run
self.configure_interfaces()
File "/home/kali/krackattacks-scripts/krackattack/./[krack-test-client.py](http://krack-test-client.py/)", line 455, in configure_interfaces
subprocess.check_output(["iw", self.nic_iface, "interface", "add", self.nic_mon, "type", "monitor"])
File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.10/subprocess.py", line 503, in run
stdout, stderr = process.communicate(input, timeout=timeout)
File "/usr/lib/python3.10/subprocess.py", line 1139, in communicate
stdout = [self.stdout.read](http://self.stdout.read/)()
KeyboardInterrupt
[11:27:39] Closing hostapd and cleaning up ...

After that I can't run the script again and the operating system freezes.
Help please, I do not know what to do. I tried reinstalling the os, drivers and the scripts, but it didn't help. I use vmware with kali and TP-Link Archer T3U [Realtek RTL8812BU]

**Comment by vanhoefm** [comment]
Did you install a custom driver for this device? There's a high chance the RTL8812BU driver doesn't support AP and/or virtual interface, meaning this dongle cannot be used with this script.
