### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'iw'

### ISSUE THREAD

**Issue by dkagel** [vanhoefm/krackattacks-scripts#92]
Getting this error when running ./krack-test-client.py:

[14:24:49] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
Traceback (most recent call last):
  File "/home/drew/krackattacks-scripts/krackattack/./krack-test-client.py", line 663, in <module>
    attack.run(options=options)
  File "/home/drew/krackattacks-scripts/krackattack/./krack-test-client.py", line 465, in run
    self.configure_interfaces()
  File "/home/drew/krackattacks-scripts/krackattack/./krack-test-client.py", line 452, in configure_interfaces
    subprocess.call(["iw", self.nic_mon, "del"], stdout=subprocess.PIPE, stdin=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'iw'
[14:24:49] Closing hostapd and cleaning up ...

**Comment by vanhoefm** [comment]
Install the package that provides the "iw" utility. On Kali/Ubuntu "sudo apt install iw" normally.
