### ISSUE TITLE
krack-test-client.py : FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

### ISSUE THREAD

**Issue by scottkid** [vanhoefm/krackattacks-scripts#93]
on kali linux 

Hello ! I need some help here please, I dont know how to fix this 
thank you

Traceback (most recent call last):
  File "/home/jm/Bureau/krackattacks-scripts/krackattack/./krack-test-client.py", line 11, in <module>
    from scapy.all import *
  File "/usr/local/lib/python3.10/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/local/lib/python3.10/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/local/lib/python3.10/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.10/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.10/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.10/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by vanhoefm** [comment]
Did you run `./pysetup.sh` and then load the python virtual environment using:

```
sudo su
source venv/bin/activate
```

and then start the script?
