### ISSUE TITLE
./krack-test-client.py --replay-broadcast running error

### ISSUE THREAD

**Issue by sakeri-l** [vanhoefm/krackattacks-scripts#96]
I turned off hardware encryption, and used ifconfig wlan0 down to disable the wireless network card. I followed the steps./krack-test-client.py --replay-broadcast reported an error, and I was using python3.11.2

[22:41:48] Note: disable Wi-Fi in network manager & disable hardware encryption. Both may interfere with this script.
command failed: Operation not supported (-95)
Traceback (most recent call last):
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 663, in <module>
    attack.run(options=options)
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 465, in run
    self.configure_interfaces()
  File "/home/kali/krackattacks-scripts/krackattack/./krack-test-client.py", line 455, in configure_interfaces
    subprocess.check_output(["iw", self.nic_iface, "interface", "add", self.nic_mon, "type", "monitor"])
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['iw', 'wlan0', 'interface', 'add', 'monwlan0', 'type', 'monitor']' returned non-zero exit status 161.
[22:41:48] Closing hostapd and cleaning up ...

**Comment by vanhoefm** [comment]
You were probably using a network card that's not supported.
