### ISSUE TITLE
L2 socket is not defined

### ISSUE THREAD

**Issue by KetCyber26** [vanhoefm/krackattacks-scripts#99]
root㉿kali)-[~/krackattacks-scripts/krackattack]
└─# python krack-test-client.py
Traceback (most recent call last):
  File "/root/krackattacks-scripts/krackattack/krack-test-client.py", line 12, in <module>
    import libwifi
  File "/root/krackattacks-scripts/krackattack/libwifi/__init__.py", line 1, in <module>
    from .wifi import *
  File "/root/krackattacks-scripts/krackattack/libwifi/wifi.py", line 204, in <module>
    class MonitorSocket(L2Socket):
                        ^^^^^^^^
NameError: name 'L2Socket' is not defined

**Comment by vanhoefm** [comment]
Execute the script in the python virtual environment. See the README.

**Comment by KetCyber26** [comment]
even though I run source venv/bin/activate it shows no directory found.I followed each step.
